[package]
name = "purple_cello_reverse_proxy"
version = "0.1.0"
edition = "2021"
description = "A reverse proxy for the Purple Cello Minecraft Server."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.21.5"
rand = "0.8.5"
async-trait = "0.1.75"
